version: "3.7"
services:
  db:
    image: "postgres:9.6-alpine"
    env_file: "./db.env"
    volumes:
      # Where $PWD is the integration directory
      - "$PWD/migrations/src/main/resources:/docker-entrypoint-initdb.d"

  rabbit:
    image: "rabbitmq:3.6-alpine"

  manager:
    depends_on:
      - "db"
      - "rabbit"
    image: "hyppo-manager" # TODO
    env_file: "./hyppo.env"
    ports:
      - "9000:9000"
    command: ["/app/target/universal/stage/bin/hyppo-manager", "-Dplay.evolutions.db.default.autoApply=true"]

  worker:
    depends_on:
      - "manager"
    image: "hyppo-manager" # TODO
    env_file: "./hyppo.env"
    command: ["/app/target/universal/stage/bin/hyppo-manager", "-main", "com.harrys.hyppo.WorkerMain", "-Dconfig.resource=application.conf"]
