version: "3.7"
services:
  db:
    image: "postgres:9.6-alpine"
    env_file: "db.env"
    volumes:
      # Where $PWD is the integration directory
      - "$PWD/migrations/src/main/resources:/docker-entrypoint-initdb.d"

  rabbit:
    image: "rabbitmq:3.6-alpine"

  manager:
    dependsOn:
      - "db"
      - "rabbit"
    image: "harrystech/hyppo-manager" # TODO
    env_file: "hyppo.env"
    ports:
      - "9000:9000"
    command: ["sbt", "run"]

  worker:
    dependsOn:
      - "manager"
    image: "harrystech/hyppo-manager" # TODO
    env_file: "hyppo.env"
    command: ["sbt", "runMain", "com.harrys.hyppo.WorkerMain", "-Dconfig.resource=application.conf"]
